# Default configuration for epsilon-sim floating platform simulation

platform:
  # Physical properties of the semi-ballasted platform
  mass: 1.25e7                 # kg, total mass (semi-ballasted condition)
  length: 120.0                # m, platform length (square platform)
  width: 120.0                 # m, platform width
  inertia_z: 8.0e9            # kg⋅m², moment of inertia about vertical axis
  
  # Platform geometry - attachment points relative to center
  attachment_points:           # m, [x, y] coordinates in body frame
    - [60.0, 60.0]            # Top-right corner
    - [-60.0, 60.0]           # Top-left corner
    - [-60.0, -60.0]          # Bottom-left corner
    - [60.0, -60.0]           # Bottom-right corner

mooring:
  # Mooring line configuration  
  num_lines: 4
  length: 300.0                # m, unstretched line length (to tugboats)
  stiffness: 1.2e9            # N, axial stiffness (EA)
  
  # Tugboat positions in global coordinate system
  anchor_positions:           # m, [x, y] coordinates
    - [280.0, 280.0]          # NE tugboat (top-right corner)
    - [-280.0, 280.0]         # NW tugboat (top-left corner)
    - [-280.0, -280.0]        # SW tugboat (bottom-left corner)
    - [280.0, -280.0]         # SE tugboat (bottom-right corner)
  
  # Line breaking configuration
  break_scenarios:
    - line_id: 0              # Which line breaks (0-3)
      break_time: 0.0         # s, time when line breaks

damping:
  # Hydrodynamic damping coefficients (reduced for oscillating motion)
  linear_coeff: 2.0e5         # N⋅s/m, linear damping in surge/sway (reduced)
  angular_coeff: 1.0e7        # N⋅m⋅s/rad, angular damping in yaw (reduced)
  
simulation:
  # Integration parameters
  duration: 120.0             # s, total simulation time
  max_timestep: 0.25          # s, maximum integration timestep
  tolerance: 1.0e-6           # relative tolerance for integration
  
  # Initial conditions
  initial_position: [0.0, 0.0, 0.0]    # [x, y, psi] in [m, m, rad]
  initial_velocity: [0.0, 0.0, 0.0]    # [dx, dy, dpsi] in [m/s, m/s, rad/s]

animation:
  # Animation and visualization settings
  speedup_factor: 6.0         # Animation speed multiplier
  fps: 30                     # Frames per second
  resolution: [1920, 1080]    # [width, height] in pixels
  loop_animation: true        # Enable continuous looping
  
  # Interactive controls
  speed_control:
    enabled: true
    min_speed: 0.1            # Minimum playback speed multiplier
    max_speed: 10.0           # Maximum playback speed multiplier
    default_speed: 1.0        # Default playback speed
  
  load_control:
    enabled: true
    min_load_factor: 0.0      # Minimum load factor (0% of original)
    max_load_factor: 2.0      # Maximum load factor (200% of original)
    default_load_factor: 1.0  # Default load factor (100% of original)
  
  # Plot limits and styling
  plot_limits: [-250, 250]    # m, symmetric plot limits
  platform_color: "black"
  line_colors: ["blue", "blue", "blue", "blue"]
  broken_line_color: "red"
  anchor_color: "red"
  anchor_marker: "x"
  anchor_size: 100
  
  # Force visualization
  force_display:
    show_force_bars: true     # Show real-time force bar chart
    show_force_values: true   # Show numerical force readouts
    color_code_lines: true    # Color-code lines by force magnitude
    force_scale_factor: 1.0e-6 # Scale factor for force display (MN)

output:
  # Output file settings
  results_dir: "output"
  video_filename: "simulation.mp4"
  data_filename: "results.csv"
  
  # Data logging
  save_trajectory: true
  save_forces: true
  save_energy: true
  log_interval: 0.1           # s, time interval for data logging 